services:
  - type: web
    name: pharmgenius-production
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    disk:
      - name: php
        size: 512
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
