services:
  - type: web
    name: medtechai-org
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    disk:
      - name: php
        size: 512
    envVars:
      - key: GROQ_API_KEY
        value: your-groq-api-key
      - key: GEMINI_API_KEY
        value: your-gemini-api-key
      - key: OPENROUTER_API_KEY
        value: your-openrouter-api-key
